# Generated by Django 5.0 on 2023-12-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created_at', models.DateTimeField(auto_now_add=True)),
                ('date_updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('REAL', 'REAL'), ('DUMMY', 'DUMMY')], max_length=230)),
                ('history', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created_at', models.DateTimeField(auto_now_add=True)),
                ('date_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created_at', models.DateTimeField(auto_now_add=True)),
                ('date_updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('EU_type', models.CharField(choices=[('PAID_BY', 'PAID_BY'), ('HAD_TO_PAY', 'HAD_TO_PAY')], max_length=255)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.expenses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created_at', models.DateTimeField(auto_now_add=True)),
                ('date_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('Expense_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.expenseuser')),
                ('G_user', models.ManyToManyField(related_name='group_user', to='SplitWiseApp.user')),
                ('admin', models.ManyToManyField(related_name='group_admin', to='SplitWiseApp.user')),
                ('participants', models.ManyToManyField(related_name='group_participants', to='SplitWiseApp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expenseuser',
            name='Expense_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.group'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.group'),
        ),
        migrations.AddField(
            model_name='expenseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.user'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.user'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='users',
            field=models.ManyToManyField(related_name='involved_expenses', to='SplitWiseApp.user'),
        ),
    ]
